# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Yen Peng
tagline:	'Home of Aspirations'
description:	'You have arrived at my experimental website.'
url:		http://yenpeng.github.io/

author:
  name:		'Yen Peng'
  url:		http://yenpeng.github.io/

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/sitecover.jpg

social:
  - icon: facebook
    url:  https://www.facebook.com/iamyenpeng
    desc: Add me on Facebook

  - icon: linkedin
    url:  https://my.linkedin.com/in/yenpenglee
    desc: View me on Linkedin

  - icon: github
    url:  https://github.com/yenpeng
    desc: Visit me on Github
    
menu:
  - title:	Home
    url:	/
    
  - title:	About
    url:	/about

  - title:  Sweat
    url:  /sweat
    
copyright:
  author:	Yen Peng
  url:		http://yenpeng.github.io
  type_title: Made with Jekyll and Thinny
  type_url: https://github.com/camporez/Thinny/releases
