# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Yen Peng
tagline:	'Site'
description:	'My experimental website.'
url:		https://yenpeng.github.io/

author:
  name:		'Yen Peng'
  url:		https://yenpeng.github.io/

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/boat.jpg

social:
  - icon: facebook
    url:  https://www.facebook.com/iamyenpeng
    desc: Add me on Facebook

  - icon: linkedin
    url:  https://my.linkedin.com/in/yenpenglee
    desc: View me on Linkedin

  - icon: github
    url:  https://github.com/yenpeng
    desc: Visit me on Github
    
menu:
  - title:	Home
    url:	/
    
  - title:	About
    url:	/about
    
copyright:
  author:	Yen Peng
  url:		https://yenpeng.github.io
